### ISSUE TITLE
Suggestions to improve figures

### ISSUE THREAD

**Issue by trangdata** [bdawkins99/BoD#4]
### Figs 1-4.
I know we haven't finalized these figures but we want to be consistent in our use of attributes vs. variables. I'll keep thinking about what's the best way to represent this data. More suggestions to come :).

### Figs. 5-6
1. I would reduce the number of trials for each distance type, e.g. `p = 10, 100, 10000`. I think three is enough to make the point.
2. I would use `facet_grid` with `scales = 'free'` to combine different values of `p` and Manhattan (left) and Euclidean (right) distances. 
3. Not sure about this one, but should we re-scale the distances? (Seeing the mean and var vary so much is a bit distracting)

**Comment by bdawkins99** [comment]
For **Figs 1-4**, I can make whatever changes we think should be made for the final figures. I intentionally avoided adding the code I used for these because it is utterly grotesque to look at/use. I had to combine aspects I liked from R and LaTeX to get these figures to look right, so I have several .R files and .tex files I used for the finished result you see in the paper. Ultimately, I think it would be easier for any changes to just be made by me as suggestions come in. Thank you for your suggestions.

For **Figs 5-6**, these are just place holders for the idea of convergence by central limit theorem. As you suggested, I think the idea is easily illustrated with fewer cases. I just used base R plot() for these because it was simple. In any case, I am not entirely sure if we need these figures in there at all. I think the audience will get the idea because this is a direct application of the Central Limit Theorem. For **3**, the mean and variance are always proportional to the number of variables `p`. This is the reason for the dynamism in these figures.

**Comment by trangdata** [comment]
Ah I see. By the way, I think the proofs are really elegant! Amazing job, @bdawkins99!

> The mean and variance are always proportional to the number of variables `p`. This is the reason for the dynamism in these figures.

Yes, I agree! But I was thinking we can say that in the main text or figure caption. A more informative statistics to add in the figure would be a measure of normality such as KL divergence. 

> I am not entirely sure if we need these figures in there at all.

I think these are helpful for visualization. I would at least keep them in the Supplement if not the main paper.

**Comment by trangdata** [comment]
All fixed so I closed this issue.
